version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: MR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Oor7iedi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MR"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: MR
      DB_USER: postgres
      DB_PASSWORD: Oor7iedi
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge